site_name: rv64.zip
copyright: '<a href="https://github.com/cyyself">Yangyu Chen</a>'
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
  icon:
    logo: material/folder-zip
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_name: 'cyyself/rv64.zip'
repo_url: 'https://github.com/cyyself/rv64.zip'